---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: 1.8.2
  values:
    installCRDs: true
    prometheus:
      enabled: false
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/arch: amd64
    webhook:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
    cainjector:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
    startupapicheck:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
  interval: 1m0s