name: Linux Self-Hosted Runner Docker Image Build

on:
  push:
    branches: ["main" ]
    paths:
      - docker/ubuntu-2004/Dockerfile
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/<REPLACE-ME>/<REPLACE-ME>:ubuntu-2004-runner-deployment
        file: docker/ubuntu-2004/Dockerfile
